In [191]:
import pandas as pd
speed = pd.read_csv("Speed.tsv", sep="\t")
speed.head()

,_id,id,device_id,record_oid,count_start_date,count_end_date,average_daily_car_traffic,average_daily_bike_traffic,counter_number,counter_type,...,longitude,latitude,neighborhood,council_district,ward,tract,public_works_division,pli_division,police_zone,fire_zone
0,1,1011743669,85,1.445865e+09,2019-04-18,2019-04-26,4949.0,NaN,6,StatTrak,...,-79.967772,40.455733,Polish Hill,7.0,6.0,42003060500,6.0,6.0,2.0,2-6
1,2,1026101993,140,1.121444e+09,2019-01-24,NaN,NaN,NaN,NaN,Intersection Study,...,-79.952249,40.466157,Central Lawrenceville,7.0,9.0,42003090200,2.0,9.0,2.0,3-6
2,3,1032382575,11,1.539893e+09,2018-08-28,2018-09-04,NaN,NaN,NaN,NaN,...,-80.076469,40.460717,Windgap,2.0,28.0,42003563000,5.0,28.0,6.0,1-16
3,4,103627606,9,7.341951e+08,2018-07-17,2018-08-01,2741.0,NaN,NaN,StatTrak,...,-79.914335,40.437379,Squirrel Hill South,5.0,14.0,42003140800,3.0,14.0,4.0,2-18
4,5,1039546167,144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-80.019211,40.490794,Perry North,1.0,26.0,42003260200,1.0,26.0,1.0,1-15

In [193]:
speed['speed_limit'] = pd.to_numeric(speed['speed_limit'], errors='coerce')
mean_speed = speed.groupby('neighborhood')['speed_limit'].mean()
sorted_mean_speed = mean_speed.sort_values()
sorted_mean_speed = sorted_mean_speed.dropna()
pd.set_option('display.max_rows', None)
sorted_mean_speed = sorted.sort_values().reset_index()
print((sorted_mean_speed))

neighborhood
Homewood South               21.666667
Hazelwood                    21.666667
South Side Slopes            24.375000
Allegheny Center             25.000000
Marshall-Shadeland           25.000000
Middle Hill                  25.000000
Morningside                  25.000000
Mount Washington             25.000000
New Homestead                25.000000
North Shore                  25.000000
Overbrook                    25.000000
Point Breeze                 25.000000
Point Breeze North           25.000000
Polish Hill                  25.000000
Regent Square                25.000000
Shadyside                    25.000000
Sheraden                     25.000000
South Shore                  25.000000
South Side Flats             25.000000
Spring Hill-City View        25.000000
Squirrel Hill North          25.000000
Squirrel Hill South          25.000000
St. Clair                    25.000000
Stanton Heights              25.000000
Strip District               25.000000
Summer Hill                  25.000000
Upper Hill                   25.000000
West Oakland                 25.000000
Manchester                   25.000000
Lower Lawrenceville          25.000000
Lincoln-Lemington-Belmar     25.000000
Crawford-Roberts             25.000000
Beechview                    25.000000
Brookline                    25.000000
California-Kirkbride         25.000000
Carrick                      25.000000
Central Business District    25.000000
Central Lawrenceville        25.000000
Central Northside            25.000000
Central Oakland              25.000000
Crafton Heights              25.000000
Lincoln Place                25.000000
Duquesne Heights             25.000000
East Allegheny               25.000000
East Hills                   25.000000
Arlington                    25.000000
East Liberty                 25.000000
Elliott                      25.000000
Allegheny West               25.000000
Fineview                     25.000000
Friendship                   25.000000
Greenfield                   25.000000
Highland Park                25.000000
Homewood North               25.000000
Knoxville                    25.000000
Larimer                      25.000000
Bluff                        25.000000
Perry North                  26.428571
Bloomfield                   27.727273
Windgap                      28.333333
Perry South                  28.333333
North Oakland                30.000000
Brighton Heights             30.000000
Westwood                     31.666667
Name: speed_limit, dtype: float64